FROM golang:1.23.0 AS builder

RUN mkdir /app
WORKDIR /app

COPY . .

RUN go build -o consumer cmd/consumer/consumer.go

FROM golang:1.23.0

WORKDIR /app

COPY --from=builder /app/consumer .

CMD ["./consumer"]
