FROM golang:1.23.0 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /src/cmd/consumer

RUN go build -o /bin/consumer

FROM alpine:latest

COPY --from=build /bin/consumer /bin/consumer

CMD ["/bin/consumer"]
